// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmnceekgzwtlltowjvka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InptbmNlZWtnend0bGx0b3dqdmthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MTQxODEsImV4cCI6MjA3Mjk5MDE4MX0.r7knV6I8zbmdO-JtTM07rBokCRop3ZzarjdZqg4y5tk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});